### PR TITLE
Fix `XP Graph`

### LINKED ISSUE #158: Fix more than 1 point per day in `XPGraph`
image
API Response:
```
[
   {
      "date":"2022-05-18",
      "amount":100
   },
   {
      "date":"2022-05-18",
      "amount":140
   },
   {
      "date":"2022-05-18",
      "amount":130
   },
   {
      "date":"2022-05-19",
      "amount":130
   }
]
```

### PR DESCRIPTION
**Pull request by JeronimoMendes**
Changed the algorithm to insert empty days and refactored some code.
Closes #158

### CODE REVIEW

File: frontend/src/components/xp/XPGraph.js [hunk 1]
```diff
@@ -2,102 +2,15 @@ import React, { useEffect, useState } from 'react';
...
-	};
-
 	const [data, setData] = useState();
 	const [maxAmount, setMaxAmount] = useState();
 
 	useEffect(() => {
 		let new_data = cleanData(props.xpEvents);
-		new_data = new_data.slice(Math.max(new_data.length - 7, 0));
-		convertToWeekDays(new_data);
+		console.log(props.xpEvents);
```
Comment (LordOfTheNeverThere) [inline frontend/src/components/xp/XPGraph.js:10]: There is a console.log in line 10, this should be removed

**Review by LordOfTheNeverThere — CHANGES_REQUESTED** [review]
