### PR TITLE
Notify user on invalid inputs or request error

### LINKED ISSUE #120: Notify user on invalid inputs or request error
Currently in Registration some form errors are not prompted to the user

-  Such as having a same email as an already registered account
- Or an incorrect username character

image

This info should be given to the user!

### PR DESCRIPTION
**Pull request by afonsofsdomingues**
Implementation of warning toasts for incorrect data inserted in the login and register pages. This includes invalid or taken usernames and email addresses, weak passwords, empty fields, and different passwords inserted in the password repetition section.

closes #120

### CODE REVIEW

File: frontend/src/components/login/LoginInput.js [hunk 1]
```diff
@@ -28,14 +28,18 @@ const LoginInput = () => {
...
 
 	const handleChangeUsername = (e) => setUsername(e.target.value);
 	const handleChangePassword = (e) => setPassword(e.target.value);
+
+	const { enqueueSnackbar } = useSnackbar();
 	
 	const handleClick = () => {
 		logIn(username, password, (error) => {
-			setError(true);
+			console.log(error.response.data);
```
Comment (JeronimoMendes) [inline frontend/src/components/login/LoginInput.js:39]: Delete debug logs

File: backend/package-lock.json [hunk 2]
```diff
@@ -0,0 +1,6 @@
+{
+  "name": "backend",
+  "lockfileVersion": 2,
+  "requires": true,
+  "packages": {}
+}
```
Comment (JeronimoMendes) [inline backend/package-lock.json:6]: Delete this file

File: package-lock.json [hunk 3]
```diff
@@ -0,0 +1,6 @@
+{
+  "name": "Arquimedia",
+  "lockfileVersion": 2,
+  "requires": true,
+  "packages": {}
+}
```
Comment (JeronimoMendes) [inline package-lock.json:6]: Delete this file

File: frontend/src/components/register/RegisterInput.js [hunk 4]
```diff
@@ -53,7 +64,16 @@ const RegisterInput = (props) => {
 				setcodePhase(true);
 			}, (error) => {
 				console.log("Something went wrong!");
-				console.log(error)
+				console.log(error.response.data);
```
Comment (JeronimoMendes) [inline frontend/src/components/register/RegisterInput.js:67]: Delete debug logs

**Review by JeronimoMendes — CHANGES_REQUESTED** [review]
Good first PR 👍
